CREATE TABLE Usuarios(
	ID SERIAL PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	Senha TEXT NOT NULL,
	TipoUsuario VARCHAR(20) NOT NULL CHECK (TipoUsuario IN ('Admin', 'Usuario')),
	DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);